### PR TITLE
All task in c

### PR DESCRIPTION
**Pull request by Utkarsh2604**

### CODE REVIEW

**Comment by Utkarsh2604** [comment]
Completed My Task

**Comment by captain-pool** [comment]
@Utkarsh2604 thanks for the contribution!
Can you place the codes under a directory called C?

**Comment by Utkarsh2604** [comment]
Hey Gnx-Nsec/Hello-World
Please could you help me here a little.

How can I move my file to a folder without disturbing my existing Pull
request..

I mean if I commit to that pull request will it be reseted?because in
hacktoberfest my pr are maturing and I don't want them to be start again?

Will you please if possible considering merging my pull request if possible!

**Comment by Utkarsh2604** [comment]
i have completed it @captain-pool
i have placed all files under one directory
please merge my pr @captain-pool

**Pull request merged**
