### PR TITLE
Add sample code for all languages in README.

### PR DESCRIPTION
**Pull request by Hamzantal**
#86

### CODE REVIEW

**Comment by captain-pool** [comment]
Hey @hamzantal. Thanks for contributing. The code samples in the README is not required. It would be nice if you can remove the whole sample section and keep only the index to the directories.

**Comment by Hamzantal** [comment]
Oh. Lol. O.o

**Comment by Hamzantal** [comment]
@captain-pool do you want to link to each folder in the README only, or the 3 code samples as well?

**Comment by Hamzantal** [comment]
@captain-pool Fixed the README and just kept the index 👍

**Comment by captain-pool** [comment]
@Hamzantal the PR looks good!

**Pull request merged**
