### PR TITLE
Hello Clojure

### PR DESCRIPTION
**Pull request by Leoperon**
Hello World in Clojure

### CODE REVIEW

**Comment by captain-pool** [comment]
Thanks for the contribution @leoperon
However there's already a commit which addresses this. Please take a look here. https://github.com/gnx-nsec/Hello-World/commit/2783025b7278a194415a86a60c792726e5bb53d6

**Comment by Leoperon** [comment]
Ok, Do I have to create a function for this?

**Comment by captain-pool** [comment]
@Leoperon it's not about the function. I meant someone already added a PR to address the issue.

**Comment by Leoperon** [comment]
Ok then I'll try to add different problems solutions in Clojure.

**Pull request closed without merging**
