### PR TITLE
Added a hello world script in bash

### PR DESCRIPTION
**Pull request by baedyl**
Added a bash script in the main directory printing "Hello world!"

### CODE REVIEW

**Comment by captain-pool** [comment]
Hi @baedyl can you complete all the problems so that I can merge the PR? Thanks :)

**Comment by baedyl** [comment]
> Hi @baedyl can you complete all the problems so that I can merge the PR? Thanks :)
Sure! No problem!

**Comment by captain-pool** [comment]
Looks good, thanks for the contribution!

**Comment by captain-pool** [comment]
Hey @baedyl can you put the codes in a folder named bash?

**Pull request merged**
