### PR TITLE
Added Programs 1 and 2 for Issue #1

### PR DESCRIPTION
**Pull request by siddhantvirus**
Issue #1

### CODE REVIEW

**Comment by captain-pool** [comment]
Hey @siddhantvirus 
I would really like if you can create a folder of the language and put the files in there.
That would really helpful.

**Comment by siddhantvirus** [comment]
@captain-pool , I did that on my local repository and forgot pushing the same folder here , sorry !
I'll fix it right away !

**Comment by siddhantvirus** [comment]
I just checked , @captain-pool  my forked repository has a folder called Python . Please merge the pull request and i believe you will see a older here as well/.

**Comment by captain-pool** [comment]
Awesome! Thanks for the contribution!

**Pull request merged**
