### PR TITLE
Add Helloworld in LOLCODE

### PR DESCRIPTION
**Pull request by Paskalouis**
Add Helloworld in LOLCODE

Ref: https://github.com/gnx-nsec/Hello-World/issues/93

### CODE REVIEW

**Comment by captain-pool** [comment]
Hey @Paskalouis. Thanks for the contribution! Can you push the solutions to other 2 problems too?

**Comment by Paskalouis** [comment]
> Hey @Paskalouis. Thanks for the contribution! Can you push the solutions to other 2 problems too?

Sure, I will add on this PR.

**Comment by Paskalouis** [comment]
Hi @captain-pool , I have added user input and loop logic in LOLCODE, please do check.
If you don't mind, you can add assignee and label on this PR :)
Thank you !

**Comment by captain-pool** [comment]
Hey @Paskalouis looks good.

**Pull request merged**
